### ISSUE TITLE
Practica 3: Induccion Matematica

### ISSUE THREAD

**Issue by UsuarioIncognito** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-pavos2#1]
[Practica_Induccion_Matematica.pdf](https://github.com/user-attachments/files/17529407/Practica_Induccion_Matematica.pdf)

**Comment by LenninGS-0** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
